[params]
author = "bugnofree"
intro = "Startup Guru Extraordinaire"
description = "Description"
authorimage = "mg.jpg" 
dateformat = "Jan 2, 2006"

[params.meta]
description = "Simple minimalist theme"
keywords = "minimalist,blog,goa,hugo,developer"

[params.social]
github = "<username>"
twitter = "<username>"
facebook = "<username>"
google = "<username>"
stackoverflow = "<username>"
email = "you@example.com"

[params.extra]
copyright = "© 2016. Erlich Bachman. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredby = true
highlightjs = true

[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
